version: '3'

services:
    #PHP Service
    serve:
        build:
            context: .
            dockerfile: Dockerfile
        image: digitalocean.com/php
        container_name: login-ui-app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
            working_dir: /var/www/login-ui-app
        volumes:
            - ./:/var/www/login-ui-app
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        depends_on:
            - mysql
            - selenium
        networks:
            - login-ui-app-network

    #Nginx Service
    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        tty: true
        ports:
            - "8070:80"
            - "445:443"
        volumes:
            - ./:/var/www/login-ui-app
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - login-ui-app-network

    #MySQL Service
    mysql:
        image: mysql:latest
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports:
            - "3313:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root 
        networks:
            - login-ui-app-network
        volumes:
            - dbdata:/var/lib/mysql
            - ./mysql/my.cnf:/etc/mysql/my.cnf
    
    #PHPMyAdmin
    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: mysql
            MYSQL_USERNAME: root
            MYSQL_ROOT_PASSWORD: root
            PMA_PORT: 3306
        ports:
            - 5002:80
        depends_on:
            - mysql
        restart: unless-stopped
        networks:
            - login-ui-app-network

    #Selenium
    selenium:
        container_name: selenium
        image: selenium/standalone-chrome
        ports:
            - 4446:4444
        restart: unless-stopped
        networks:
            - login-ui-app-network

#Docker Networks
networks:
    login-ui-app-network:
        driver: bridge

#Volumes
volumes:
    dbdata:
        driver: local
